"""Migration

Revision ID: 9221f60123a5
Revises: d99e298c0309
Create Date: 2025-04-22 14:41:53.693393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9221f60123a5'
down_revision = 'd99e298c0309'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('link', 'short_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('link', sa.Column('short_url', sa.TEXT(), nullable=False))
    # ### end Alembic commands ###
