"""Migration

Revision ID: d99e298c0309
Revises: 2ad1a32981f5
Create Date: 2025-04-22 13:37:51.867744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd99e298c0309'
down_revision = '2ad1a32981f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('link', sa.Column('short_url', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('link', 'short_url')
    # ### end Alembic commands ###
